### ISSUE TITLE
release version 1.0.1.Final

### ISSUE THREAD

**Issue by smiklosovic** [arquillian/arquillian-droidium#17]
@aslakknutsen @MatousJobanek 

please release version 1.0.1.Final of Droidium.

Everything is ready and tested and works as expected. The release has to be 1.0.1.Final as this version is in archetype.

It is not necessary to execute any tests anymore and ordinary maven release process should do it.

The next development iteration is 1.0.2-SNAPSHOT

Thanks a lot

**Comment by aslakknutsen** [comment]
released, pushed to nexus.

Any release notes?

**Comment by smiklosovic** [comment]
@aslakknutsen 

"The second final release of Arquillian Droidium does not comes with new functionality but it repairs some minor bugs and updates almost all dependencies to the latest and gratest. With the dedication of JBoss team, we are cutting new releases very often and dependecies of Droidium tend to get obsolete quite soon. This release brings Selendroid 0.17, Arquillian Core 1.1.10.Final, Arquillian Recorder 1.1.0.Final and Graphene 2.1.0.Alpha3 with Drone 2.0.0.Alpha5.

If you are looking for the tool by which you could functionally test your native and hybrid Android applications, look no further - Droidium stands on the shoulders of titans - Arquillian Core, Graphene and Drone."

**Comment by aslakknutsen** [comment]
done ! 

Thank you :)
